# Generated by Django 4.2.6 on 2024-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0002_document_document_document_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='device',
            field=models.CharField(default='', max_length=120),
        ),
    ]
