# Generated by Django 4.2.6 on 2024-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0003_document_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='media/signs'),
        ),
    ]
