# Generated by Django 4.2.6 on 2024-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0004_document_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
