# Generated by Django 4.2.6 on 2024-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0005_document_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='elictricity',
            field=models.ImageField(blank=True, null=True, upload_to='media/elitricity'),
        ),
        migrations.AddField(
            model_name='document',
            name='water',
            field=models.ImageField(blank=True, null=True, upload_to='media/water'),
        ),
    ]
