# Generated by Django 4.2.6 on 2024-03-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0006_document_elictricity_document_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='photo',
        ),
        migrations.CreateModel(
            name='Detail_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media/room_details')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acting.detail')),
            ],
        ),
    ]
