# Generated by Django 4.2.6 on 2024-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0008_alter_detail_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='elictiricity_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gas',
            field=models.ImageField(blank=True, null=True, upload_to='media/gs'),
        ),
        migrations.AddField(
            model_name='document',
            name='gas_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='landlord',
            field=models.CharField(default='landlord', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.CharField(default='tenant', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='water_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
