# Generated by Django 4.2.6 on 2024-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0009_document_elictiricity_text_document_gas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys_image', models.ImageField(blank=True, null=True, upload_to='media/keys')),
                ('door', models.CharField(max_length=100)),
                ('mailbox', models.CharField(max_length=1000)),
                ('k_from_b', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('remote_contrls', models.CharField(max_length=100)),
                ('ac_controls', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
