# Generated by Django 4.2.6 on 2024-03-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0010_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acting.document'),
        ),
    ]
