# Generated by Django 4.2.6 on 2024-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0012_keys_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='apartment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='building',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='device',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='landlord',
            field=models.CharField(blank=True, default='landlord', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.CharField(blank=True, default='tenant', max_length=100, null=True),
        ),
    ]
