# Generated by Django 4.2.6 on 2024-04-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0013_alter_document_apartment_alter_document_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=1500)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acting.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Element_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/room_details')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acting.element')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail_photo',
        ),
    ]
