# Generated by Django 4.2.6 on 2024-04-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0014_element_element_photo_delete_detail_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tenant',
        ),
        migrations.CreateModel(
            name='OwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acting.document')),
            ],
        ),
    ]
