# Generated by Django 4.2.6 on 2024-04-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0016_remove_document_sign_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='author',
            field=models.CharField(default='opium', max_length=150),
        ),
    ]
