# Generated by Django 4.2.6 on 2024-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0017_sign_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='email',
            field=models.CharField(default='opium', max_length=80),
        ),
        migrations.AddField(
            model_name='sign',
            name='email',
            field=models.CharField(default='opium', max_length=80),
        ),
    ]
