# Generated by Django 4.2.6 on 2024-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0018_ownership_email_sign_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='media/signs'),
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
