# Generated by Django 5.0.4 on 2024-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0021_document_is_visible_alter_detail_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='media/previews'),
        ),
    ]
