# Generated by Django 5.0.4 on 2024-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0023_remove_document_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='media/preview'),
        ),
    ]
