version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 100M
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis

  redis:
    image: redis

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.python
    command: >
      sh -c "celery -A acting beat --loglevel=info &&
             celery -A acting worker --loglevel=info -P eventlet" # Change eventlet to gevent for lighter worker pool
    volumes:
      - ./backend:/app/backend
    depends_on:
      - app
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5173:5173"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 100M
    volumes:
      - ./front:/app/front
    depends_on:
      - app
