# Generated by Django 4.2.6 on 2024-02-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
