# Generated by Django 4.2.6 on 2024-02-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_remove_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_proved',
            field=models.BooleanField(default=False),
        ),
    ]
