# Generated by Django 4.2.6 on 2024-02-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_user_is_proved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_look',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
