# Generated by Django 4.2.6 on 2024-02-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_user_password_look'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=1243, null=True),
        ),
    ]
