# Generated by Django 4.2.6 on 2024-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_user_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
